services:
  auth-db:
    image: postgres:16
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: auth
    volumes:
      - auth-db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
  
  auth-migrations:
    build:
      context: .
    environment:
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_URL: auth-db
      DATABASE_NAME: auth
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
    command: ["flask", "--app", "app.py", "db", "upgrade"]
    volumes:
      - ./migrations:/app/migrations
    depends_on:
      auth-db:
        condition: service_healthy
        restart: true
    restart: "no"
  
  auth:
    build:
      context: .
    environment:
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_URL: auth-db
      DATABASE_NAME: auth
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
    ports:
      - "5000:5000"
    volumes:
      - ./migrations:/app/migrations
    depends_on:
      auth-migrations:
        condition: service_completed_successfully
        restart: true

volumes:
  auth-db-data:
