services:
  store-db:
    image: postgres:16
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: store
    networks:
      - store-net
    volumes:
      - store-db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
  
  store-migrations:
    build:
      context: .
      dockerfile: owner/Dockerfile
    command: ["flask", "--app", "owner.app", "db", "upgrade"]
    environment:
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_URL: store-db
      DATABASE_NAME: store
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
    networks:
      - store-net
    volumes:
      - ./common/migrations:/app/migrations
    depends_on:
      store-db:
        condition: service_healthy
        restart: true
    restart: "no"
  
  owner:
    build:
      context: .
      dockerfile: owner/Dockerfile
    environment:
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_URL: store-db
      DATABASE_NAME: store
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
    ports:
      - "5001:5000"
    networks:
      - store-net
    volumes:
      - ./common/migrations:/app/migrations
    depends_on:
      store-migrations:
        condition: service_completed_successfully
        restart: true
  
  customer:
    build:
      context: .
      dockerfile: customer/Dockerfile
    environment:
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_URL: store-db
      DATABASE_NAME: store
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
    ports:
      - "5002:5000"
    networks:
      - store-net
    volumes:
      - ./common/migrations:/app/migrations
    depends_on:
      store-migrations:
        condition: service_completed_successfully
        restart: true
  
  courier:
    build:
      context: .
      dockerfile: courier/Dockerfile
    environment:
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_URL: store-db
      DATABASE_NAME: store
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
    ports:
      - "5003:5000"
    networks:
      - store-net
    volumes:
      - ./common/migrations:/app/migrations
    depends_on:
      store-migrations:
        condition: service_completed_successfully
        restart: true

networks:
  store-net:

volumes:
  store-db-data:
