"""Initial migration

Revision ID: c5e62343d515
Revises: 
Create Date: 2026-04-21 19:48:53.962985

"""
from alembic import op
import sqlalchemy as sa
from werkzeug.security import generate_password_hash


# revision identifiers, used by Alembic.
revision = 'c5e62343d515'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('forename', sa.String(length=256), nullable=False),
    sa.Column('surname', sa.String(length=256), nullable=False),
    sa.Column('email', sa.String(length=256), nullable=False),
    sa.Column('password', sa.String(length=256), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )

    users = sa.table(
        "users",
        sa.column("forename", sa.String),
        sa.column("surname", sa.String),
        sa.column("email", sa.String),
        sa.column("password", sa.String),
        sa.column("role", sa.String),
    )

    op.bulk_insert(
        users,
        [
            {
                "forename": "Scrooge",
                "surname": "McDuck",
                "email": "onlymoney@gmail.com",
                "password": generate_password_hash("evenmoremoney"),
                "role": "owner",
            }
        ]
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # users = sa.table(
    #     "users",
    #     sa.column("email", sa.String),
    # )

    # op.execute(
    #     users.delete().where(users.c.email == "onlymoney@gmail.com")
    # )

    op.drop_table('users')
    # ### end Alembic commands ###
